### ISSUE TITLE
Dark theme font to white

### ISSUE THREAD

**Issue by janzenz** [liamjohnston/comic-slack#14]
How about inverted colour on dark theme, e.g. white?

**Comment by liamjohnston** [comment]
There's no way to detect dark theme. These are just emojis. 
A given slack organisation will have a mix of users using dark mode and normal mode. Since dark mode came along, I've had to bake a background colour into the emoji.

**Comment by janzenz** [comment]
I mean how about adding a dark mode toggle on the Comic-slack converter form to produce a white/black colour?

**Comment by liamjohnston** [comment]
But the point is that the message author has no control over whether their recipients have dark mode or not (in reality it will probably be a mix of both).

**Comment by janzenz** [comment]
ah true, didn't think of that.
